nicer animation flow for dismiss on swipe
nispok/snackbar pull request #135
Opened 2015-07-14 17:30 UTC by Valodim

...maybe "different" animation flow is a less opinionated term here.

as was, snackbars are moved in from the bottom and are affixed to both screen edges (on non-tablet screens). I never quite liked how swiping the snackbar exposed the left or right edge, breaking its "full width, moved in from bottom" vibe. swiping it down to dismiss, as the guidelines say, is not very intuitive either.

this commit is a compromise which keeps side-swiping while keeping the edges fixed: swiping behavior is unchanged, but now only the *content* of the snackbar is moved, while the snackbar (i.e. its background) fades out but stays in place.

I tried different animations for actually dismissing the background afterwards, and fading it out the rest of the way felt better than moving it off the bottom of the screen for the swipe flow.

related note: your library has several advantages over the one from the support library, please keep maintaining it! :+1:

2015-08-06 12:05 UTC, Valodim commented
ping?

if you like the old animation better, feel free to close the PR.

2015-08-06 12:06 UTC, merged

2015-08-06 12:06 UTC, wmora commented
:)

2015-08-06 12:12 UTC, wmora commented
@Valodim sorry about the delay. I meant to publish this days ago. Just published it as version 2.11.0

2025-06-19 01:03 UTC, annelota1 approved these changes

2025-07-06 10:26 UTC, annelota1 requested changes
Please solve my sms problem